# Generated by Django 3.1.7 on 2021-06-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Image_field',
        ),
    ]
